# Config file for automatic testing at travis-ci.org
language: python

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set auto_update_conda no
  - conda update -q conda

install:
  - conda update python -cconda-forge
  - conda env update -n root -f environment.yml
  - conda install pytest-cov black pytest pytest-cov codecov -cconda-forge
  - conda install xorg-libx11 xorg-libxtst -cconda-forge
  - conda list

script:
  - black . -l120 --exclude "external/*"
  - python setup.py install
  - pytest -v --color=yes --cov-report term-missing --cov=biorbd_optim tests

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always
