# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: biorbd_optim
channels:
- conda-forge
- default
dependencies:
- python
- numpy
- matplotlib
- casadi
- rbdl =*=*casadi*
- biorbd =*=*casadi*
- biorbd-viz =*=*casadi*
- scipy
- packaging
